### ISSUE TITLE
Security groups

### ISSUE THREAD

**Issue by lisenet** [aws-samples/aws-elastic-beanstalk-hardened-security-cdk-sample#11]
Does this approach control the Beanstalk application's (running on EC2 instances) **outbound** access to the Internet in any way (e.g. a security group or NACL), or do you allow all traffic to pass uninterrupted to the outside by design?

**Comment by LaurensBrinker** [comment]
There's no NACL defined, but there are security groups on each layer of the setup (LB / Web / DB).

For web specifically, we allow outbound HTTP traffic to any IP (inbound is restricted to LB). However, this can be tweaked by setting the `webserverOutboundCIDR` parameter in `cdk.json`. 

Code where this is taken into account: https://github.com/aws-samples/aws-elastic-beanstalk-hardened-security-cdk-sample/blob/main/lib/elastic_beanstalk_cdk_project-stack.ts#L184

It's been a while since I worked on that part, but if iirc, it's necessary to e.g. pull dependencies for the app from the internet for this sample.

**Comment by lisenet** [comment]
This is brilliant, thank you!
